name: motorcycle_management
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # HTTP untuk koneksi API Laravel
  http: ^1.1.0

  # Local storage untuk token auth
  shared_preferences: ^2.2.2

  # Secure storage untuk tokens (persistent login)
  flutter_secure_storage: ^9.0.0

  # Firebase untuk push notification
  firebase_core: ^3.12.1
  firebase_messaging: ^15.2.4
  flutter_local_notifications: ^18.0.1
  device_info_plus: ^11.2.0

  # UUID untuk device ID
  uuid: ^4.5.1

  # JSON handling
  json_annotation: ^4.8.1
  fl_chart: ^0.68.0
  flutter_svg: ^2.2.0
  image_picker: ^1.2.0
  excel: ^4.0.6
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  open_file: ^3.3.2
  file_picker: ^10.3.3
  intl: ^0.20.2
  flutter_map: ^8.3.0
  latlong2: ^0.9.1
  url_launcher: ^6.3.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # Build runner untuk JSON
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.4

flutter:
  uses-material-design: true
  generate: true

  # Assets
  assets:
    - assets/images/
    - assets/icon/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_ikon.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/icon/app_ikon.png"

flutter_native_splash:
  color: "#ffffff"
  image: "assets/icon/app_ikon.png"
  android: true
  ios: true
